pool:
  name: Azure Pipelines
  demands: maven

steps:
- task: Maven@3
  displayName: 'Maven app/pom.xml'
  inputs:
    mavenPomFile: app/pom.xml
    codeCoverageToolOption: Cobertura

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App Service'
  inputs:
    azureSubscription: 'b184036a-5180-4167-a04d-fbe745b0fe61'
    appType: 'webApp'
    WebAppName: 'javaspringboot-app'
    packageForLinux: '$(System.DefaultWorkingDirectory)/_CICD Yaml-Maven-CI/drop/app/target/gs-spring-boot-0.1.0.jar'
    StartupCommand: '$(Parameters.StartupCommand)'